#pragma once

#define DEVICE_NAME       CONFIG_DEVICE_NAME
#define SAMPLE_SIZE       CONFIG_SAMPLE_SIZE
#define WIFI_SSID         CONFIG_WIFI_SSID
#define WIFI_PASS         CONFIG_WIFI_PASS
#define SERVER_URL        CONFIG_SERVER_URL
#define API_KEY           CONFIG_API_KEY
#define ENDPOINT          CONFIG_ENDPOINT
#define INTERVAL_MS       CONFIG_INTERVAL_MS
#define WIFI_TIMEOUT_MS   CONFIG_WIFI_TIMEOUT_MS
#define TCP_TIMEOUT_MS    CONFIG_TCP_TIMEOUT_MS
